# -*- coding: utf-8 -*-
"""pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skvlY-0xcWps3cW2Ri_jD3uNLR4F08N1
"""

pip install pdfplumber

import pdfplumber
import json
import os


def extract_table_from_pdf(pdf_path):
    extracted_data = []

    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            text = page.extract_text()

            if text:
                lines = text.split("\n")

                for line in lines:
                    columns = line.split()

                    if len(columns) > 2:
                        extracted_data.append(columns)

    return extracted_data


def convert_to_json(table_data):
    structured_data = []

    for row in table_data:
        row_dict = {}
        for i, value in enumerate(row):
            row_dict[f"column_{i+1}"] = value

        structured_data.append(row_dict)

    return structured_data


def main():
    pdf_path = input("Enter the PDF file path: ")

    if not os.path.exists(pdf_path):
        print("Invalid file path!")
        return

    print("Processing PDF...")

    table_data = extract_table_from_pdf(pdf_path)
    json_data = convert_to_json(table_data)

    output_file = "output.json"

    with open(output_file, "w") as f:
        json.dump(json_data, f, indent=4)

    print(f"Extraction complete. JSON saved as {output_file}")


if __name__ == "__main__":
    main()